modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Stuff-A-Sock-In-It"

[[mods]]
modId="sasit"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.sasit]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sasit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"